### ISSUE TITLE
Create a profile

### ISSUE THREAD

**Issue by rfuehrer** [generaliinformatik/mycoradar#12]
the internal profile for the repository must be created and filed in the designated place. 

Responsible:
@rfuehrer @dehesselle

**Comment by rfuehrer** [comment]
The profile has been created and is stored as part of the internal documentation. A review is done by viewing the internal filing.

Note: As the profile contains sensitive information, it is subject to data protection and will not be published here.

**Comment by rfuehrer** [comment]
Profile is ready to be reviewed. Asking @dehesselle to be man of the hour :)

**Comment by dehesselle** [comment]
Reviewed internal documents, no findings.
